/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_lame_LameActivity */

#ifndef _Included_ffmpeg_jni
#define _Included_ffmpeg_jni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_research_amr2mp3_FFmpegUtil_jniRun
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
