/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_lame_LameActivity */

#ifndef _Included_lame_jni
#define _Included_lame_jni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_research_amr2mp3_LameUtil_jniConvertmp3
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
